### PR TITLE
Added Picacoin support

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mraksoll4** [comment]
Cannot be tested , no avaliable mac os and linux wallets

**Comment by mraksoll4** [comment]
Where i can find pre-compiled linux wallet/daemon with cli ?

**Comment by picacoin** [comment]
> Where i can find pre-compiled linux wallet/daemon with cli ?

It should be on Github, I just added it yesterday after seeing this comment. https://github.com/picacoin/picacoin/releases/

**Comment by picacoin** [comment]
@mraksoll4 You can get them here http://picacoin.org/ 😁

**Pull request closed without merging**
